MODEL:

  PRETRAIN_CHOICE: 'self'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 1.0
  CTL_LOSS_WEIGHT : 0.0
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_LOSS_WEIGHT : 1.0
  TEMPERATURE: 1.0
  TRANSFORMER_TYPE: 'swin_base_patch4_window7_224'
  SEMANTIC_WEIGHT: 0.2
  PRETRAIN_PATH : "/home/swin_base_tea.pth"
  REDUCE_FEAT_DIM: False
  FEAT_DIM: 1024
  SIE_CAMERA: False
  SIE_COE:  1.0
#  DROPOUT_RATE: 0.0


INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY:  1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 40
    CHECKPOINT_PERIOD: 60
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 5
  
  STAGE2:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "SGD"
    BASE_LR: 0.0002
    WARMUP_EPOCHS: 20
    WARMUP_METHOD: cosine
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    LARGE_FC_LR: False
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 130
    LOG_PERIOD: 20
    EVAL_PERIOD: 120
    BIAS_LR_FACTOR: 2
    STEPS: [40, 70]
    GAMMA: 0.1

  STAGE3:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    MOMENTUM: 0.9
    WARMUP_EPOCHS:  5
    WEIGHT_DECAY: 1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 5
    CHECKPOINT_PERIOD: 60
    LOG_PERIOD: 20
    EVAL_PERIOD: 5
    BIAS_LR_FACTOR: 2
    BASE_LR: 0.0002
    GAMMA: 0.1
    NUM_HARD_SAMPLER: 16
    LAYER:  4
    RESID_PDROP: 0.1
    AFN: 'gelu'

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT:  "/home/ViT-B-16_120.pth"
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

DATASETS:
   NAMES: ('dukemtmc')
   ROOT_DIR: ('/home/')
OUTPUT_DIR: 'log/dukemtmc'

